/**:
  ekf_filter_node:
    ros__parameters:
      frequency: 30.0
      sensor_timeout: 0.1
      two_d_mode: true
      publish_tf: true

      # map_frame: map
      odom_frame: odom
      base_link_frame: base_footprint
      world_frame: odom

      odom0: odom_raw
      odom0_config: [true, true, false,
                    false, false, true,
                    true, true, false,
                    false, false, true,
                    false, false, false]
      odom0_queue_size: 10
      odom0_pose_rejection_threshold: 20.0
      odom0_twist_rejection_threshold: 1.542

      imu0: imu
      imu0_config: [false, false, false,
                    false, false, true,
                    false, false, false,
                    false, false, true,
                    false, false, false]
      imu0_differential: false
      imu0_relative: true
      imu0_queue_size: 10
      imu0_pose_rejection_threshold: 20.0
      imu0_twist_rejection_threshold: 1.542
      imu0_linear_acceleration_rejection_threshold: 10.0

      use_control: false